FROM prom/alertmanager:?ALERTMANAGER_VERSION?

ENV \
    ARG_COMMAND=/bin/alertmanager \
    ARG_PREFIX=ALERTMGR_ \
    ALERTMGR_STORAGE_PATH=/alertmanager

ADD entrypoint.sh /entrypoint
ENTRYPOINT [ "/entrypoint" ]
